server:
  port: 9082
  contextPath: /pos

spring:
  data:
    jpa:
      repositories:
        enabled: true
#    maxPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      hbm2ddl.auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: OITH_PROJECT_DB_USER
    password: OITH_PROJECT_DB_PASS
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 123456
    protocol: smtp
  messages:
    always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
    basename: i18n/messages # Comma-separated list of basenames, each following the ResourceBundle convention.
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    encoding: UTF-8 # Message bundles encoding.
    fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.



#smtp.host=smtp.gmail.com
#smtp.port=587
#smtp.protocol=smtp
#smtp.username=
#smtp.password=123456
#
#mail.smtp.starttls.enable=true
#mail.smtp.auth=true
#mail.transport.protocol=smtp
#mail.debug=true

#---hibernate
#
#---hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#---hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#---hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#---hibernate.dialect=org.hibernate.dialect.DerbyTenSevenDialect
#---hibernate.dialect=org.hibernate.dialect.H2Dialect
#---hibernate.dialect=org.hibernate.dialect.MySQLDialect
#---hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#
#---hibernate.dialect=org.hibernate.dialect.DerbyTenSevenDialect
#
#---hibernate.archive.autodetection=class
#---hibernate.generate_statistics=true
#---hibernate.cache.provider_class=org.hibernate.cache.EhCacheProvider
#---hibernate.cache.region.factory_class=net.sf.ehcache.hibernate.EhCacheRegionFactory
#---hibernate.cache.use_query_cache=false
#---hibernate.cache.use_second_level_cache=false
#---hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
#---hibernate.format_sql=true
#---hibernate.hbm2ddl.auto=update
#---hibernate.show_sql=false
#---hibernate.enable_lazy_load_no_trans=true
#
#---jdbc
#
#---#jdbc.driverClassName=oracle.jdbc.OracleDriver
#---#jdbc.driverClassName=org.postgresql.Driver
#---#jdbc.driverClassName=org.apache.derby.jdbc.ClientDriver
#---#jdbc.driverClassName=org.h2.Driver
#---#jdbc.driverClassName=com.mysql.jdbc.Driver
#---#jdbc.driverClassName=com.microsoft.jdbc.sqlserver.SQLServerDriver
#
#---#jdbc.url=jdbc:oracle:thin:@localhost:1521:xe
#---#jdbc.url=jdbc:postgresql://localhost:5432/testdb
#---#jdbc.url=jdbc:derby://localhost:1527/sample
#---#jdbc.url=jdbc:h2:~/test
#---#jdbc.url=jdbc:mysql://localhost:3306/test
#---#jdbc.url=jdbc:microsoft:sqlserver://localhost:1433;DatabaseName=DATABASE